-- Add concise origin and meaning data for SSA girls ranked 101-200.
-- Existing Elo ratings, votes, rooms, and participants are untouched.

begin;

create temporary table ssa_etymology_101_200 (
  display_name text primary key,
  origin text,
  meaning text
) on commit drop;

insert into ssa_etymology_101_200 (display_name, origin, meaning) values
  ('Aaliyah', 'Arabic', 'exalted, high-born'),
  ('Margot', 'French / Greek', 'pearl'),
  ('Allison', 'English / Germanic', 'noble kind'),
  ('Hailey', 'English', 'hay meadow'),
  ('Gabriella', 'Hebrew', 'God is my strength'),
  ('Parker', 'English', 'park keeper'),
  ('Anna', 'Hebrew', 'grace, favor'),
  ('Cecilia', 'Latin', 'from the Roman family name Caecilius'),
  ('Athena', 'Greek', 'goddess of wisdom and strategy'),
  ('Juliette', 'French / Latin', 'youthful'),
  ('Catalina', 'Spanish / Greek', 'pure'),
  ('Margaret', 'Greek', 'pearl'),
  ('Cora', 'Greek', 'maiden'),
  ('Rose', 'Latin', 'rose flower'),
  ('Eliza', 'Hebrew', 'God is my oath'),
  ('Raelynn', 'Modern American', 'modern blend of Rae and Lynn'),
  ('Alaia', 'Basque', 'joyful, happy'),
  ('Brooklyn', 'English', 'place name; brook or stream'),
  ('Esther', 'Persian / Hebrew', 'star'),
  ('Hallie', 'English', 'dweller at the meadow or hall'),
  ('Hadley', 'English', 'heather field'),
  ('Emerson', 'English / Germanic', 'son of Emery'),
  ('Elsie', 'Scottish / Hebrew', 'pledged to God'),
  ('Magnolia', 'French / Latin', 'magnolia flower'),
  ('Mary', 'Hebrew', 'beloved; traditionally also bitter or wished-for child'),
  ('Scottie', 'Scottish / English', 'from Scotland'),
  ('Valerie', 'Latin', 'strong, healthy'),
  ('Ariana', 'Greek / Welsh', 'most holy; silver'),
  ('Serenity', 'English / Latin', 'peacefulness, calm'),
  ('Alina', 'Slavic / Germanic', 'bright, beautiful'),
  ('Julia', 'Latin', 'youthful'),
  ('Amira', 'Arabic', 'princess, commander'),
  ('Charlie', 'French / Germanic', 'free person'),
  ('Eva', 'Hebrew', 'life'),
  ('Savannah', 'Spanish / Taino', 'open plain'),
  ('Bella', 'Italian / Latin', 'beautiful'),
  ('Rylee', 'Irish / English', 'courageous; rye clearing'),
  ('Emersyn', 'Modern English', 'modern spelling of Emerson'),
  ('Elliana', 'Hebrew / Latin', 'God has answered; bright one'),
  ('Alana', 'Irish / Germanic', 'beautiful; precious'),
  ('Sloane', 'Irish', 'raider, warrior'),
  ('Melanie', 'Greek', 'dark, black'),
  ('Brielle', 'French / Hebrew', 'God is my strength'),
  ('Natalia', 'Latin', 'Christmas Day, birth'),
  ('Remi', 'French / Latin', 'oarsman, remedy'),
  ('Aubrey', 'French / Germanic', 'elf ruler'),
  ('Evangeline', 'Greek', 'bearer of good news'),
  ('Genevieve', 'French / Germanic', 'woman of the people'),
  ('Kehlani', 'Hawaiian-inspired modern name', 'sea and sky'),
  ('June', 'Latin', 'associated with Juno, queen of the gods'),
  ('Samantha', 'Hebrew / Aramaic', 'listener; God has heard'),
  ('Summer', 'English', 'summer season'),
  ('Oaklynn', 'Modern English', 'oak tree and lake or waterfall'),
  ('Ember', 'English', 'glowing coal'),
  ('Piper', 'English', 'pipe or flute player'),
  ('Oakley', 'English', 'oak clearing'),
  ('Phoebe', 'Greek', 'bright, radiant'),
  ('Arya', 'Sanskrit / Persian', 'noble, honorable'),
  ('Wrenley', 'Modern English', 'wren bird with a modern suffix'),
  ('Sage', 'Latin / English', 'wise; aromatic herb'),
  ('Alani', 'Hawaiian', 'orange tree'),
  ('Valeria', 'Latin', 'strong, healthy'),
  ('Anastasia', 'Greek', 'resurrection'),
  ('Ashley', 'English', 'ash tree clearing'),
  ('Nevaeh', 'Modern American', 'heaven spelled backward'),
  ('Isabelle', 'French / Hebrew', 'God is my oath'),
  ('Skylar', 'Dutch / English', 'scholar'),
  ('Ailani', 'Hawaiian', 'high chief'),
  ('Blair', 'Scottish', 'plain, field'),
  ('Gemma', 'Italian / Latin', 'gem, precious stone'),
  ('Rosalie', 'French / Latin', 'rose'),
  ('Vivienne', 'French / Latin', 'alive, lively'),
  ('Ruth', 'Hebrew', 'friend, companion'),
  ('Ariella', 'Hebrew', 'lion of God'),
  ('Callie', 'Greek / English', 'beautiful'),
  ('Freya', 'Old Norse', 'lady; goddess of love and beauty'),
  ('Isabel', 'Spanish / Hebrew', 'God is my oath'),
  ('Daphne', 'Greek', 'laurel tree'),
  ('Lilah', 'Arabic / Hebrew', 'night; delicate'),
  ('Amaya', 'Basque / Japanese', 'the end; night rain'),
  ('Sutton', 'English', 'south settlement'),
  ('Annie', 'Hebrew', 'grace, favor'),
  ('Ximena', 'Spanish / Basque', 'listener'),
  ('Adalynn', 'Modern English / Germanic', 'noble one'),
  ('Kaylani', 'Modern Hawaiian-inspired', 'sea and sky'),
  ('Katherine', 'Greek', 'pure'),
  ('Lila', 'Arabic / Sanskrit', 'night; play'),
  ('Celeste', 'Latin', 'heavenly'),
  ('Tatum', 'English', 'Tata’s homestead'),
  ('Haven', 'English', 'safe harbor'),
  ('Blakely', 'English', 'dark woodland clearing'),
  ('Reese', 'Welsh', 'enthusiasm, ardor'),
  ('Kaia', 'Scandinavian / Greek', 'pure; earth'),
  ('Everleigh', 'Modern English', 'wild boar meadow'),
  ('Alora', 'Modern English / African usage', 'dreamer; my dream'),
  ('Molly', 'English / Hebrew', 'beloved; traditional diminutive of Mary'),
  ('Olive', 'Latin', 'olive tree, peace'),
  ('Sara', 'Hebrew', 'princess'),
  ('Peyton', 'English', 'fighting-man’s estate'),
  ('Lia', 'Italian / Hebrew', 'weary; bearer of good news');

update public.names n
set origin = e.origin,
    meaning = e.meaning
from ssa_etymology_101_200 e
where n.display_name = e.display_name;

commit;

select display_name, ssa_rank, origin, meaning
from public.names
where ssa_rank between 101 and 200
order by ssa_rank;
