create extension if not exists pgcrypto;

create table public.rooms (
  id uuid primary key default gen_random_uuid(),
  token text not null unique default upper(substr(encode(gen_random_bytes(6), 'hex'), 1, 8)),
  created_at timestamptz not null default now()
);

create table public.participants (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 40),
  access_token uuid not null unique default gen_random_uuid(),
  created_at timestamptz not null default now(),
  unique (room_id, display_name)
);

create table public.names (
  id bigint generated by default as identity primary key,
  display_name text not null unique,
  ssa_rank integer,
  source text not null default 'curated',
  created_at timestamptz not null default now()
);

create table public.rankings (
  participant_id uuid not null references public.participants(id) on delete cascade,
  name_id bigint not null references public.names(id) on delete cascade,
  rating numeric(8,2) not null default 1500,
  wins integer not null default 0,
  losses integer not null default 0,
  comparisons integer not null default 0,
  primary key (participant_id, name_id)
);

create table public.votes (
  id bigint generated by default as identity primary key,
  participant_id uuid not null references public.participants(id) on delete cascade,
  left_name_id bigint not null references public.names(id),
  right_name_id bigint not null references public.names(id),
  winner_name_id bigint not null references public.names(id),
  created_at timestamptz not null default now(),
  check (left_name_id <> right_name_id),
  check (winner_name_id = left_name_id or winner_name_id = right_name_id)
);

create index votes_participant_created_idx on public.votes(participant_id, created_at desc);
create index participants_room_idx on public.participants(room_id);

alter table public.rooms enable row level security;
alter table public.participants enable row level security;
alter table public.names enable row level security;
alter table public.rankings enable row level security;
alter table public.votes enable row level security;

create policy "names are publicly readable"
on public.names for select
to anon, authenticated
using (true);

create or replace function public.create_room(owner_name text)
returns table(room_token text, participant_token uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  new_room public.rooms;
  new_participant public.participants;
begin
  insert into public.rooms default values returning * into new_room;
  insert into public.participants(room_id, display_name)
  values (new_room.id, trim(owner_name))
  returning * into new_participant;

  return query select new_room.token, new_participant.access_token;
end;
$$;

create or replace function public.join_room(join_token text, participant_name text)
returns table(room_token text, participant_token uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_room public.rooms;
  new_participant public.participants;
begin
  select * into target_room
  from public.rooms
  where token = upper(trim(join_token));

  if target_room.id is null then
    raise exception 'Room not found';
  end if;

  insert into public.participants(room_id, display_name)
  values (target_room.id, trim(participant_name))
  returning * into new_participant;

  return query select target_room.token, new_participant.access_token;
end;
$$;

grant execute on function public.create_room(text) to anon, authenticated;
grant execute on function public.join_room(text, text) to anon, authenticated;
