-- Ensure every ranked name displays origin and meaning without fabricating etymology.
-- Existing curated metadata remains authoritative. This migration adds a set of
-- well-established etymologies, then uses an explicit uncertainty label for any
-- name whose derivation is not reliably established in the current catalog.

alter table public.names add column if not exists origin text;
alter table public.names add column if not exists meaning text;

update public.names n
set origin = v.origin,
    meaning = v.meaning
from (values
  ('Olivia','Latin','olive tree'),
  ('Charlotte','French / Germanic','free woman'),
  ('Emma','Germanic','whole, universal'),
  ('Amelia','Germanic','work, industrious'),
  ('Sophia','Greek','wisdom'),
  ('Mia','Italian / Scandinavian','mine; beloved'),
  ('Isabella','Hebrew via Italian','pledged to God'),
  ('Evelyn','English / Norman French','desired; wished-for child'),
  ('Sofia','Greek','wisdom'),
  ('Ava','Germanic / Latin','life; bird'),
  ('Eleanor','Old French','meaning uncertain; often associated with light'),
  ('Violet','Latin / English','violet flower'),
  ('Aurora','Latin','dawn'),
  ('Harper','English','harp player'),
  ('Elizabeth','Hebrew','God is my oath'),
  ('Lily','English / Latin','lily flower'),
  ('Camila','Latin','young ceremonial attendant'),
  ('Nora','Irish / Latin','honor; light'),
  ('Hazel','English','hazel tree'),
  ('Penelope','Greek','traditional meaning uncertain; associated with weaving'),
  ('Chloe','Greek','young green shoot'),
  ('Lucy','Latin','light'),
  ('Aria','Italian / Hebrew','air, melody; lioness'),
  ('Luna','Latin','moon'),
  ('Isla','Scottish','island'),
  ('Ella','Germanic / English','all, complete; fairy maiden'),
  ('Zoe','Greek','life'),
  ('Scarlett','English','scarlet red'),
  ('Gianna','Italian / Hebrew','God is gracious'),
  ('Emily','Latin','rival; striving'),
  ('Valentina','Latin','strong, healthy'),
  ('Layla','Arabic','night'),
  ('Avery','English / Germanic','elf ruler'),
  ('Grace','Latin','grace, favor'),
  ('Ivy','English','ivy plant'),
  ('Madison','English','son of Matthew'),
  ('Abigail','Hebrew','my father is joy'),
  ('Elena','Greek','shining light'),
  ('Mila','Slavic','gracious, dear'),
  ('Willow','English','willow tree'),
  ('Emilia','Latin','rival; striving'),
  ('Nova','Latin','new'),
  ('Naomi','Hebrew','pleasantness'),
  ('Riley','Irish / English','valiant; rye clearing'),
  ('Eloise','French / Germanic','healthy; wide'),
  ('Sadie','Hebrew / English','princess'),
  ('Delilah','Hebrew','delicate'),
  ('Stella','Latin','star'),
  ('Josephine','French / Hebrew','God will add'),
  ('Victoria','Latin','victory'),
  ('Sophie','Greek','wisdom'),
  ('Hannah','Hebrew','grace, favor'),
  ('Lillian','English / Latin','lily'),
  ('Leah','Hebrew','meaning uncertain; traditionally weary'),
  ('Adeline','French / Germanic','noble'),
  ('Leilani','Hawaiian','heavenly flower; royal child'),
  ('Iris','Greek','rainbow'),
  ('Maya','Sanskrit / Greek','illusion; good mother'),
  ('Clara','Latin','bright, clear'),
  ('Ruby','Latin / English','red gemstone'),
  ('Alice','Germanic','noble'),
  ('Genesis','Greek','origin, beginning'),
  ('Claire','French / Latin','bright, clear'),
  ('Eden','Hebrew','delight'),
  ('Daisy','English','day''s eye; daisy flower'),
  ('Maeve','Irish','intoxicating'),
  ('Ayla','Turkish / Hebrew','halo around the moon; oak tree'),
  ('Liliana','Latin','lily'),
  ('Melody','Greek / English','song, melody'),
  ('Lyla','Arabic','night'),
  ('Lucia','Latin','light'),
  ('Audrey','English','noble strength'),
  ('Maria','Hebrew via Latin','meaning uncertain; traditional form of Mary'),
  ('Autumn','English','autumn season'),
  ('Natalie','Latin','born at Christmas'),
  ('Sarah','Hebrew','princess'),
  ('Lydia','Greek','woman from Lydia'),
  ('Sienna','Italian','from Siena; reddish-brown earth pigment'),
  ('Jade','Spanish / English','jade stone'),
  ('Caroline','French / Germanic','free woman'),
  ('Quinn','Irish','descendant of Conn; wise'),
  ('Amara','Multiple','grace; eternal; bitter'),
  ('Georgia','Greek','farmer, earth-worker'),
  ('Juniper','Latin / English','juniper tree'),
  ('Aaliyah','Arabic','exalted, highborn'),
  ('Margot','French / Greek','pearl'),
  ('Gabriella','Hebrew via Italian','God is my strength'),
  ('Anna','Hebrew','grace'),
  ('Cecilia','Latin','blind; name of the musical patron saint'),
  ('Athena','Greek','goddess of wisdom'),
  ('Juliette','Latin via French','youthful'),
  ('Catalina','Greek via Spanish','pure'),
  ('Cora','Greek','maiden'),
  ('Rose','Latin','rose flower'),
  ('Eliza','Hebrew via English','God is my oath'),
  ('Esther','Persian / Hebrew','star'),
  ('Hallie','English','meaning uncertain; often a diminutive of Harriet or Halle'),
  ('Magnolia','Latin / French','magnolia flower'),
  ('Mary','Hebrew','meaning uncertain; traditional form of Miriam'),
  ('Ariana','Welsh / Italian','silver; most holy'),
  ('Julia','Latin','youthful'),
  ('Amira','Arabic','princess'),
  ('Eva','Hebrew','life'),
  ('Savannah','Spanish / English','open grassy plain'),
  ('Bella','Italian','beautiful'),
  ('Alana','Celtic / Germanic','meaning varies; often linked to harmony or noble'),
  ('Sloane','Irish','raider, warrior'),
  ('Melanie','Greek','dark, black'),
  ('Brielle','French / Hebrew','God is my strength'),
  ('Natalia','Latin','born at Christmas'),
  ('Aubrey','Germanic / French','elf ruler'),
  ('Evangeline','Greek','bearer of good news'),
  ('Genevieve','French / Germanic','tribe woman'),
  ('June','Latin','of Juno'),
  ('Summer','English','summer season'),
  ('Ember','English','glowing coal'),
  ('Piper','English','pipe player'),
  ('Phoebe','Greek','bright, radiant'),
  ('Sage','Latin / English','wise; sage herb'),
  ('Anastasia','Greek','resurrection'),
  ('Ashley','English','ash-tree clearing'),
  ('Gemma','Italian / Latin','gem'),
  ('Ruth','Hebrew','friend, companion'),
  ('Freya','Norse','lady; goddess Freyja'),
  ('Daphne','Greek','laurel tree'),
  ('Annie','Hebrew via English','grace'),
  ('Katherine','Greek','pure'),
  ('Celeste','Latin','heavenly'),
  ('Reese','Welsh','enthusiasm, ardor'),
  ('Kaia','Multiple','meaning varies by language and usage'),
  ('Molly','English / Irish','beloved'),
  ('Olive','Latin','olive tree'),
  ('Peyton','English','Paega''s town'),
  ('Mabel','Latin','lovable'),
  ('Vera','Slavic / Latin','faith; true'),
  ('Jasmine','Persian','jasmine flower'),
  ('Zara','Arabic / Hebrew','radiance; princess'),
  ('Arabella','Latin / Scottish','meaning uncertain; often associated with prayer or lovability'),
  ('Dahlia','Swedish / botanical','dahlia flower'),
  ('Ada','Germanic','noble'),
  ('River','English','river'),
  ('Jane','Hebrew via English','God is gracious'),
  ('Elise','Hebrew via French','God is my oath'),
  ('Noa','Hebrew','motion'),
  ('Gracie','Latin / English','grace'),
  ('Kiara','Irish / Italian','dark; bright'),
  ('Rory','Irish','red king'),
  ('Wren','English','wren bird'),
  ('Maisie','Scottish / Greek','pearl'),
  ('Andrea','Greek','strong, courageous'),
  ('Nyla','Arabic / modern usage','one who succeeds; meaning varies'),
  ('Alexandra','Greek','defender of humankind'),
  ('Lucille','French / Latin','light'),
  ('Camille','French / Latin','young ceremonial attendant'),
  ('Delaney','Irish / French','descendant of the challenger; from the alder grove'),
  ('Diana','Roman / Latin','divine; moon goddess'),
  ('Miriam','Hebrew','meaning uncertain; traditional source of Mary'),
  ('Reagan','Irish','little king'),
  ('Rowan','Irish / Scottish','little red one; rowan tree'),
  ('Rachel','Hebrew','ewe'),
  ('Rosemary','Latin / English','dew of the sea; rosemary herb'),
  ('Faith','English / Latin','faith'),
  ('Amy','French / Latin','beloved'),
  ('Leila','Arabic','night'),
  ('Mariana','Latin / Hebrew','of Marius; related to Mary'),
  ('Ophelia','Greek','help, benefit'),
  ('Talia','Hebrew','dew from God'),
  ('Aspen','English','aspen tree'),
  ('Selena','Greek','moon'),
  ('Evie','Hebrew via English','life'),
  ('Luciana','Latin','light'),
  ('Juliet','Latin / French','youthful'),
  ('Lola','Spanish','sorrows'),
  ('Harmony','Greek / English','harmony, concord'),
  ('Lilith','Akkadian / Hebrew tradition','of the night'),
  ('Azalea','Greek / botanical','azalea flower'),
  ('Lena','Multiple','meaning varies; often light or woman of Magdala'),
  ('Shiloh','Hebrew','meaning uncertain; biblical place name'),
  ('Sylvie','French / Latin','of the forest'),
  ('Rosie','Latin / English','rose'),
  ('Meadow','English','meadow'),
  ('Adelaide','Germanic','noble nature'),
  ('Aurelia','Latin','golden'),
  ('Poppy','Latin / English','poppy flower'),
  ('Maggie','Greek via English','pearl'),
  ('Blake','English','dark or pale'),
  ('Dakota','Dakota language','ally, friend'),
  ('Leia','Hebrew / literary','weary; literary usage'),
  ('Esme','French / Persian','esteemed; beloved'),
  ('Sylvia','Latin','of the forest'),
  ('Daniela','Hebrew via Romance languages','God is my judge'),
  ('Kimberly','English','Cyneburg''s field'),
  ('Elaine','Old French / Greek','bright, shining'),
  ('Joanna','Hebrew via Greek','God is gracious'),
  ('Francesca','Italian / Latin','French woman; free'),
  ('Octavia','Latin','eighth'),
  ('Elodie','French / Germanic','foreign riches'),
  ('Tessa','Greek / English','harvester; summer'),
  ('Morgan','Welsh','sea-born; sea circle'),
  ('Brooke','English','small stream'),
  ('Catherine','Greek','pure'),
  ('Amina','Arabic','trustworthy, faithful'),
  ('Colette','French / Greek','victory of the people'),
  ('Sabrina','Celtic / Latin','of the River Severn'),
  ('Nina','International','little girl; grace'),
  ('Serena','Latin','calm, serene'),
  ('Hattie','Germanic via English','home ruler'),
  ('Mira','Latin / Slavic / Sanskrit','wonderful; peace; ocean'),
  ('Heidi','Germanic','noble'),
  ('Teagan','Irish / Welsh','poet; fair'),
  ('Paige','English / French','page, attendant'),
  ('Rebecca','Hebrew','to bind, join'),
  ('Hope','English','hope'),
  ('Thea','Greek','goddess'),
  ('Gwendolyn','Welsh','white ring; blessed bow'),
  ('Camilla','Latin','young ceremonial attendant'),
  ('Helena','Greek','shining light'),
  ('Matilda','Germanic','battle-mighty'),
  ('Astrid','Norse','divinely beautiful'),
  ('Vanessa','Literary','name coined by Jonathan Swift'),
  ('Laura','Latin','laurel'),
  ('Demi','French / Greek','half; of Demeter'),
  ('Giselle','Germanic / French','pledge'),
  ('Nicole','Greek via French','victory of the people'),
  ('Kira','Multiple','meaning varies; often throne, ruler, or dark'),
  ('Carmen','Spanish / Latin / Hebrew','song; garden'),
  ('Sunny','English','sunny, cheerful'),
  ('Florence','Latin','flourishing'),
  ('Jocelyn','Germanic / French','member of the Gauts'),
  ('Regina','Latin','queen'),
  ('Bonnie','Scottish','pretty, good'),
  ('Lauren','Latin','from Laurentum; laurel'),
  ('Taylor','English','tailor'),
  ('Raven','English','raven bird'),
  ('Carolina','Germanic via Romance languages','free woman'),
  ('Brynn','Welsh','hill'),
  ('Angela','Greek','messenger'),
  ('Finley','Scottish / Irish','fair warrior'),
  ('Holly','English','holly tree'),
  ('Joy','English','joy'),
  ('Melissa','Greek','honeybee'),
  ('Dorothy','Greek','gift of God'),
  ('Willa','Germanic','resolute protector'),
  ('Opal','Sanskrit via English','gem, precious stone'),
  ('Winter','English','winter season'),
  ('Veronica','Greek / Latin','meaning uncertain; traditional name'),
  ('Trinity','Latin / English','threefold unity'),
  ('Leona','Latin','lioness'),
  ('London','English','place name; etymology uncertain'),
  ('Dream','English','dream'),
  ('Vienna','Place name','from Vienna'),
  ('Lyra','Greek','lyre'),
  ('Salem','Hebrew / Arabic','peace'),
  ('Alma','Latin / Spanish / Hebrew','nourishing; soul; young woman'),
  ('Calliope','Greek','beautiful voice'),
  ('Clementine','Latin / French','merciful, gentle'),
  ('Helen','Greek','shining light'),
  ('Meredith','Welsh','great ruler'),
  ('Fiona','Scottish','fair, white'),
  ('Maren','Latin / Scandinavian','of the sea'),
  ('Felicity','Latin','happiness, good fortune'),
  ('Winnie','Welsh / English','blessed peacemaking; fair one'),
  ('Renata','Latin','reborn'),
  ('Ainsley','Scottish / English','one''s own meadow'),
  ('Arielle','Hebrew','lion of God'),
  ('Amanda','Latin','worthy of love'),
  ('Arlette','French / Germanic','noble'),
  ('Solana','Spanish / Latin','sunny place'),
  ('Maxine','Latin / French','greatest'),
  ('Edith','English','prosperous in war'),
  ('Bianca','Italian','white'),
  ('Mae','English','May; pearl'),
  ('Yara','Arabic / Brazilian tradition','small butterfly; water lady'),
  ('Beatrice','Latin','she who brings happiness'),
  ('Faye','English','fairy'),
  ('Louise','Germanic / French','renowned warrior'),
  ('Clover','English','clover plant'),
  ('Eve','Hebrew','life'),
  ('Amber','Arabic / English','amber gemstone'),
  ('Kate','Greek via English','pure'),
  ('Virginia','Latin','maiden'),
  ('Lottie','French / Germanic','free woman'),
  ('Cecelia','Latin','blind; musical patron'),
  ('Skye','Scottish','Isle of Skye'),
  ('Phoenix','Greek','dark red; phoenix bird'),
  ('April','Latin / English','April month'),
  ('Angel','Greek','messenger'),
  ('Danielle','Hebrew via French','God is my judge'),
  ('Holland','Dutch / English place name','woodland'),
  ('Fernanda','Germanic via Spanish','bold voyager'),
  ('Frankie','Germanic / English','free person'),
  ('Alexis','Greek','helper, defender'),
  ('Stephanie','Greek','crown'),
  ('Jacqueline','Hebrew via French','supplanter'),
  ('Margo','French / Greek','pearl'),
  ('Mavis','French / English','song thrush'),
  ('Della','Germanic / English','noble'),
  ('Nadia','Slavic / Arabic','hope; tender'),
  ('Amalia','Germanic','work'),
  ('Allie','Multiple','diminutive form; meaning depends on source name'),
  ('Estelle','Latin / French','star'),
  ('Cleo','Greek','glory'),
  ('Imani','Swahili','faith'),
  ('Reina','Spanish / Yiddish','queen; pure'),
  ('Noemi','Hebrew via Romance languages','pleasantness'),
  ('Jennifer','Welsh','white wave; fair one'),
  ('Chaya','Hebrew','life'),
  ('Mara','Hebrew / Slavic','bitter; sea'),
  ('Marigold','English','marigold flower'),
  ('Paris','Greek / place name','name from Greek legend and the city'),
  ('Halle','Germanic / place name','home ruler; from Halle'),
  ('Mina','Multiple','meaning varies; often love, fish, or protector'),
  ('Seraphina','Hebrew / Latin','fiery, burning'),
  ('Marina','Latin','of the sea'),
  ('Flora','Latin','flower; spring goddess'),
  ('Marie','Hebrew via French','traditional form of Mary'),
  ('Anne','Hebrew','grace'),
  ('Goldie','English / Yiddish','golden'),
  ('Selene','Greek','moon'),
  ('Winona','Dakota language','firstborn daughter'),
  ('Cassandra','Greek','meaning uncertain; Trojan prophetess'),
  ('Gabrielle','Hebrew via French','God is my strength'),
  ('Destiny','English / Latin','destiny, fate'),
  ('Rhea','Greek','flowing; Titan goddess'),
  ('Lyric','Greek / English','lyric song'),
  ('Thalia','Greek','to blossom; muse of comedy'),
  ('Irene','Greek','peace'),
  ('Rosa','Latin','rose'),
  ('Eileen','Irish','bright, shining'),
  ('Gloria','Latin','glory'),
  ('Miranda','Latin','worthy of admiration'),
  ('Hana','Multiple','flower; happiness; grace'),
  ('Noor','Arabic','light'),
  ('Jessica','Literary / Hebrew','name popularized by Shakespeare; God beholds'),
  ('Jolene','Modern English','modern elaboration of Jo'),
  ('Marisol','Spanish','sea and sun; devotional contraction'),
  ('Birdie','English','little bird'),
  ('Sasha','Russian / Greek','defender of humankind'),
  ('Georgina','Greek','farmer, earth-worker'),
  ('Billie','English / Germanic','resolute protector'),
  ('Louisa','Germanic','renowned warrior'),
  ('Romy','German / Latin','rose; Roman'),
  ('Robin','Germanic / English','bright fame; robin bird'),
  ('Drew','Greek / Welsh','strong; wise'),
  ('Angelica','Greek / Latin','angelic, messenger'),
  ('Leslie','Scottish','garden of holly'),
  ('Martha','Aramaic','lady, mistress'),
  ('Ryan','Irish','little king'),
  ('Lennox','Scottish','elm grove'),
  ('Remy','French / Latin','oarsman; remedy'),
  ('Sol','Spanish / Latin','sun'),
  ('Samira','Arabic','evening companion'),
  ('Bridget','Irish','exalted one'),
  ('Gwen','Welsh','white, blessed'),
  ('Theodora','Greek','gift of God'),
  ('Kathryn','Greek','pure'),
  ('Ramona','Spanish / Germanic','wise protector'),
  ('Laurel','Latin / English','laurel tree'),
  ('Persephone','Greek','meaning uncertain; queen of the underworld'),
  ('Monica','Latin / North African','meaning uncertain'),
  ('Veda','Sanskrit','knowledge'),
  ('Penny','Greek via English','weaver'),
  ('Emerald','Greek / English','emerald gemstone'),
  ('Valery','Latin / French','strong, healthy'),
  ('Dani','Hebrew','God is my judge'),
  ('Mikayla','Hebrew via modern English','who is like God?'),
  ('Davina','Hebrew via Scottish','beloved'),
  ('Karina','Latin / Scandinavian','pure; beloved'),
  ('Adele','Germanic / French','noble'),
  ('Bethany','Aramaic / Hebrew','house of figs'),
  ('Soleil','French','sun'),
  ('Marilyn','English','blend of Mary and Lynn'),
  ('Christina','Greek / Latin','follower of Christ'),
  ('Dulce','Latin / Spanish','sweet'),
  ('Freyja','Norse','lady; goddess Freyja'),
  ('Celia','Latin','heavenly'),
  ('Pearl','English / Latin','pearl'),
  ('Evelina','Germanic / English','desired; wished-for child'),
  ('Fallon','Irish','leader'),
  ('Luella','English','famous warrior; fairy maiden'),
  ('Ruthie','Hebrew via English','friend, companion'),
  ('Paulina','Latin','small, humble'),
  ('Belen','Spanish / Hebrew','Bethlehem'),
  ('Ocean','Greek / English','ocean'),
  ('Judith','Hebrew','woman from Judea'),
  ('Paloma','Spanish','dove'),
  ('Cielo','Spanish','sky, heaven'),
  ('Dalia','Hebrew / Arabic / Lithuanian','branch; gentle; fate'),
  ('Janelle','Hebrew via French','God is gracious'),
  ('Kaitlyn','Greek via Irish / English','pure'),
  ('Karla','Germanic','free woman'),
  ('Dylan','Welsh','great tide'),
  ('Treasure','English','treasure'),
  ('Zainab','Arabic','fragrant flower; father''s precious jewel'),
  ('Kelsey','English','Cenel''s island'),
  ('Aura','Latin / Greek','breeze'),
  ('Livia','Latin','blue; envious'),
  ('Nola','Irish / Latin','noble; white shoulder'),
  ('Promise','English','promise'),
  ('Amelie','French / Germanic','work, industrious'),
  ('Zelda','Germanic / Yiddish','gray fighting maid; blessed'),
  ('Erin','Irish','Ireland'),
  ('Ezra','Hebrew','help'),
  ('Denver','French / English place name','green valley'),
  ('Luz','Spanish','light'),
  ('Hunter','English','hunter'),
  ('Michaela','Hebrew','who is like God?'),
  ('Honey','English','honey; sweetheart'),
  ('Tara','Irish / Sanskrit','hill; star'),
  ('Lea','Hebrew / English','weary; meadow'),
  ('Kendra','English / Welsh','knowing; greatest champion'),
  ('Magdalena','Greek / Hebrew','woman from Magdala'),
  ('Chelsea','English place name','chalk landing place'),
  ('Kelly','Irish','warrior; bright-headed'),
  ('Indigo','Greek / English','indigo dye'),
  ('Paula','Latin','small, humble'),
  ('Nala','African / literary','meaning varies by language and usage'),
  ('Darcy','French / Irish','from Arcy; dark one'),
  ('Jamie','Hebrew via English','supplanter'),
  ('Deborah','Hebrew','bee'),
  ('Eleanora','Old French','meaning uncertain; form of Eleanor'),
  ('Mercy','English / Latin','mercy, compassion'),
  ('Soraya','Persian','the Pleiades'),
  ('Johanna','Hebrew via Greek','God is gracious'),
  ('Adrianna','Latin','from Hadria'),
  ('Julie','Latin / French','youthful'),
  ('Marianna','Latin / Hebrew','of Marius; related to Mary'),
  ('Giovanna','Hebrew via Italian','God is gracious'),
  ('Tiffany','Greek','manifestation of God'),
  ('Odette','Germanic / French','wealth'),
  ('Rebekah','Hebrew','to bind, join'),
  ('Aviana','Latin / modern usage','birdlike; modern elaboration'),
  ('Megan','Welsh / Greek','pearl'),
  ('Leanna','Multiple','meaning varies; often grace or meadow'),
  ('Anais','Hebrew / Persian via French','grace; goddess Anahita'),
  ('Guinevere','Welsh','white shadow; fair one'),
  ('Liora','Hebrew','my light'),
  ('Linda','Spanish / Germanic','pretty; soft, tender'),
  ('Luisa','Germanic via Spanish / Italian','renowned warrior'),
  ('Greta','Greek via German','pearl'),
  ('Teresa','Greek','meaning uncertain; traditionally harvester'),
  ('Eliora','Hebrew','God is my light'),
  ('Giuliana','Latin via Italian','youthful'),
  ('Raina','Slavic / Hebrew','queen; song'),
  ('Cheyenne','Place / ethnonym','from the Cheyenne people'),
  ('Emmeline','Germanic / French','work; industrious'),
  ('Winifred','Welsh / English','blessed peacemaking'),
  ('Clare','Latin / English','bright, clear'),
  ('Elisabeth','Hebrew','God is my oath'),
  ('Brittany','French place name','from Brittany'),
  ('Etta','English / Germanic','little one; home ruler'),
  ('Landry','French / Germanic','ruler of the land'),
  ('Kimber','English','from Kimberly'),
  ('Salma','Arabic','safe, peaceful'),
  ('Tallulah','Choctaw / Irish tradition','leaping water; abundance'),
  ('Darla','English','darling'),
  ('Elara','Greek','mythological name; meaning uncertain'),
  ('Mariella','Hebrew via Italian','traditional form related to Mary'),
  ('Sunday','English','Sunday'),
  ('Marcella','Latin','young warrior'),
  ('Sky','English','sky'),
  ('Milena','Slavic','gracious, dear'),
  ('Yuna','Multiple','meaning varies by language and usage'),
  ('Anika','Sanskrit / Germanic','grace; sweet-faced'),
  ('Love','English','love'),
  ('Malaysia','Place name','from Malaysia'),
  ('Yasmin','Persian / Arabic','jasmine flower'),
  ('August','Latin','great, venerable'),
  ('Nancy','Hebrew via English','grace'),
  ('Barbara','Greek','foreign woman'),
  ('Zora','Slavic','dawn'),
  ('Arden','English / literary','great forest; valley of the eagle'),
  ('Cordelia','Celtic / literary','meaning uncertain; literary royal name'),
  ('Khadija','Arabic','premature child; early-born'),
  ('Akira','Japanese','bright, clear'),
  ('Lisa','Hebrew via English','God is my oath'),
  ('Annika','Hebrew / Germanic via Scandinavian','grace'),
  ('Scout','English','one who scouts'),
  ('Simone','French / Hebrew','heard')
) as v(display_name, origin, meaning)
where n.display_name = v.display_name;

-- Never invent a specific origin or meaning for a name whose derivation has not
-- been reliably established. Give it an explicit, honest metadata label instead.
update public.names
set origin = coalesce(nullif(trim(origin), ''), 'Uncertain / modern usage'),
    meaning = coalesce(nullif(trim(meaning), ''), 'etymology not reliably established')
where ssa_rank between 1 and 1000;

-- Preserve the comparison function's name + metadata payload.
create or replace function public.get_next_pair(p_access_token uuid)
returns table(
  left_id bigint,
  left_name text,
  right_id bigint,
  right_name text,
  comparison_count integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_participant public.participants;
  first_choice public.rankings;
begin
  select * into target_participant
  from public.participants
  where access_token = p_access_token;

  if target_participant.id is null then
    raise exception 'Invalid participant token';
  end if;

  insert into public.rankings (participant_id, name_id)
  select target_participant.id, n.id
  from public.names n
  on conflict (participant_id, name_id) do nothing;

  select r.* into first_choice
  from public.rankings r
  where r.participant_id = target_participant.id
  order by r.comparisons asc, random()
  limit 1;

  return query
  select
    first_choice.name_id,
    concat_ws(E'\n', ln.display_name, nullif(trim(concat_ws(' · ', ln.origin, ln.meaning)), '')),
    r2.name_id,
    concat_ws(E'\n', rn.display_name, nullif(trim(concat_ws(' · ', rn.origin, rn.meaning)), '')),
    (select count(*)::integer from public.votes v where v.participant_id = target_participant.id)
  from public.rankings r2
  join public.names ln on ln.id = first_choice.name_id
  join public.names rn on rn.id = r2.name_id
  where r2.participant_id = target_participant.id
    and r2.name_id <> first_choice.name_id
  order by r2.comparisons asc,
           abs(r2.rating - first_choice.rating) asc,
           random()
  limit 1;
end;
$$;

grant execute on function public.get_next_pair(uuid) to anon, authenticated;

-- Hard validation: all 1,000 ranked names must now have visible metadata.
do $$
declare
  ranked_count integer;
  complete_count integer;
begin
  select count(*) into ranked_count
  from public.names
  where ssa_rank between 1 and 1000;

  select count(*) into complete_count
  from public.names
  where ssa_rank between 1 and 1000
    and nullif(trim(origin), '') is not null
    and nullif(trim(meaning), '') is not null;

  if ranked_count <> 1000 or complete_count <> 1000 then
    raise exception
      'Metadata validation failed: % ranked names, % with complete metadata; expected 1000/1000',
      ranked_count, complete_count;
  end if;
end;
$$;

select
  count(*) filter (where ssa_rank between 1 and 1000) as ranked_names,
  count(*) filter (
    where ssa_rank between 1 and 1000
      and nullif(trim(origin), '') is not null
      and nullif(trim(meaning), '') is not null
  ) as names_with_metadata,
  count(*) filter (
    where ssa_rank between 1 and 1000
      and origin = 'Uncertain / modern usage'
  ) as explicitly_unresolved
from public.names;
