-- Metadata quality pass.
-- Corrects established names and spelling variants that should not have been
-- labeled unresolved. Truly uncertain modern forms retain a short honest label.

update public.names n
set origin = v.origin,
    meaning = v.meaning
from (values
  ('Lyla','Arabic / English','night; also an English form related to Lyle'),
  ('Zoe','Greek','life'),
  ('Zoey','Greek','life'),
  ('Lila','Arabic / Sanskrit','night; divine play'),
  ('Layla','Arabic','night'),
  ('Laila','Arabic','night'),
  ('Leyla','Arabic via Turkish','night'),
  ('Leila','Arabic','night'),
  ('Lylah','Arabic / English','night; variant of Lyla'),
  ('Mya','Greek / Sanskrit','great; illusion'),
  ('Myla','Modern English / Slavic','modern form associated with Mila; gracious, dear'),
  ('Mylah','Modern English / Slavic','modern form associated with Mila; gracious, dear'),
  ('Kylie','Australian English / Irish','boomerang; graceful'),
  ('Kyla','Scottish','narrow channel'),
  ('Kira','Multiple','throne; ruler; dark'),
  ('Keira','Irish','dark-haired'),
  ('Kiara','Irish / Italian','dark; bright'),
  ('Kara','Italian / Norse','dear; wild stormy one'),
  ('Kayla','Hebrew / Arabic','crown; wise child'),
  ('Arianna','Greek / Italian','most holy'),
  ('Ariana','Greek / Welsh','most holy; silver'),
  ('Ariella','Hebrew','lion of God'),
  ('Arielle','Hebrew','lion of God'),
  ('Eliana','Hebrew / Latin','my God has answered; of the sun'),
  ('Elianna','Hebrew / Latin','my God has answered; of the sun'),
  ('Elliana','Hebrew / Latin','my God has answered; of the sun'),
  ('Ellianna','Hebrew / Latin','my God has answered; of the sun'),
  ('Alina','Slavic / Germanic','bright; noble'),
  ('Alena','Slavic','bright, shining'),
  ('Elina','Greek / Nordic','bright, shining'),
  ('Adalyn','Germanic','noble'),
  ('Adalynn','Germanic','noble'),
  ('Adelyn','Germanic','noble'),
  ('Adelynn','Germanic','noble'),
  ('Adaline','Germanic / French','noble'),
  ('Madeline','Hebrew via French','woman from Magdala'),
  ('Madelyn','Hebrew via English','woman from Magdala'),
  ('Madelynn','Hebrew via English','woman from Magdala'),
  ('Madilyn','Hebrew via English','woman from Magdala'),
  ('Madilynn','Hebrew via English','woman from Magdala'),
  ('Maddison','English','son of Matthew'),
  ('Maddie','English','diminutive of Madeline or Madison'),
  ('Lilly','Latin / English','lily flower'),
  ('Lillie','Latin / English','lily flower'),
  ('Lilian','Latin / English','lily flower'),
  ('Lilliana','Latin','lily flower'),
  ('Lilianna','Latin','lily flower'),
  ('Emely','Latin / Germanic','rival; industrious'),
  ('Emelia','Latin','rival; striving'),
  ('Emmeline','Germanic / French','work, industrious'),
  ('Emmie','Germanic / English','universal; industrious'),
  ('Emmy','Germanic / English','universal; industrious'),
  ('Evelynn','English / Norman French','desired; wished-for child'),
  ('Everly','English','wild boar clearing'),
  ('Everleigh','English','wild boar clearing'),
  ('Everlee','English','wild boar clearing'),
  ('Rylee','Irish / English','valiant; rye clearing'),
  ('Ryleigh','Irish / English','valiant; rye clearing'),
  ('Rylie','Irish / English','valiant; rye clearing'),
  ('Raelynn','Modern English','modern compound of Rae and Lynn'),
  ('Raelyn','Modern English','modern compound of Rae and Lynn'),
  ('Raegan','Irish','little king'),
  ('Reyna','Spanish','queen'),
  ('Rayna','Slavic / Hebrew','queen; song'),
  ('Raina','Slavic / Hebrew','queen; song'),
  ('Siena','Italian place name','from Siena'),
  ('Sienna','Italian place name','from Siena; reddish-brown pigment'),
  ('Juliana','Latin','youthful'),
  ('Julianna','Latin','youthful'),
  ('Julietta','Latin via Italian','youthful'),
  ('Juliette','Latin via French','youthful'),
  ('Gabriela','Hebrew via Spanish','God is my strength'),
  ('Gabriella','Hebrew via Italian','God is my strength'),
  ('Gabrielle','Hebrew via French','God is my strength'),
  ('Daniela','Hebrew via Romance languages','God is my judge'),
  ('Daniella','Hebrew via Romance languages','God is my judge'),
  ('Alyssa','Greek','rational; alyssum flower'),
  ('Alissa','Greek / Hebrew','rational; great happiness'),
  ('Alicia','Germanic via Spanish','noble'),
  ('Alisson','Germanic via French','noble'),
  ('Alison','Germanic via French','noble'),
  ('Allison','Germanic via French','noble'),
  ('Isabel','Hebrew via Spanish','God is my oath'),
  ('Isabelle','Hebrew via French','God is my oath'),
  ('Izabella','Hebrew via Italian / Polish','God is my oath'),
  ('Isabela','Hebrew via Spanish / Portuguese','God is my oath'),
  ('Mariam','Hebrew / Arabic','traditional form of Mary'),
  ('Maryam','Hebrew / Arabic','traditional form of Mary'),
  ('Mariah','Hebrew via English','traditional form related to Mary'),
  ('Mariela','Hebrew via Spanish','traditional form related to Mary'),
  ('Mariel','Hebrew via French / Spanish','traditional form related to Mary'),
  ('Mckenna','Irish','son of Cionaoith; beloved of Aodh'),
  ('Mckenzie','Scottish','son of Coinneach'),
  ('Mckinley','Scottish','son of Fionnlagh'),
  ('Makenzie','Scottish','son of Coinneach'),
  ('Makenna','Irish','son of Cionaoith; beloved of Aodh'),
  ('Oakley','English','oak clearing'),
  ('Oaklee','English','oak clearing'),
  ('Oakleigh','English','oak clearing'),
  ('Oaklyn','Modern English','modern form built from oak'),
  ('Oaklynn','Modern English','modern form built from oak'),
  ('Oaklee','English','oak clearing'),
  ('Paisley','Scottish place name','church or cemetery'),
  ('Paislee','Scottish place name','variant of Paisley'),
  ('Paislee','Scottish place name','variant of Paisley'),
  ('Brooklyn','Dutch / English place name','from Brooklyn'),
  ('Brooklynn','Dutch / English place name','variant of Brooklyn'),
  ('Brynlee','Welsh / English','hill meadow'),
  ('Brynleigh','Welsh / English','hill meadow'),
  ('Brynlee','Welsh / English','hill meadow'),
  ('Wrenley','Modern English','modern elaboration of Wren'),
  ('Wrenlee','Modern English','modern elaboration of Wren'),
  ('Wrenleigh','Modern English','modern elaboration of Wren'),
  ('Ainsley','Scottish / English','one''s own meadow'),
  ('Haisley','Modern English','modern surname-style name; exact origin uncertain'),
  ('Hadley','English','heather field'),
  ('Hadlee','English','variant of Hadley; heather field'),
  ('Kensley','Modern English','modern surname-style name'),
  ('Kinsley','English','king''s meadow'),
  ('Kinslee','English','variant of Kinsley; king''s meadow'),
  ('Kinsleigh','English','variant of Kinsley; king''s meadow'),
  ('Maci','French / English','weapon; variant of Macy'),
  ('Macie','French / English','weapon; variant of Macy'),
  ('Macy','French / English','weapon; from Massy'),
  ('Maisy','Scottish / Greek','pearl'),
  ('Maizie','Scottish / Greek','pearl'),
  ('Mazie','Scottish / Greek','pearl'),
  ('Katalina','Greek via Spanish','pure'),
  ('Kataleya','Spanish botanical','cattleya orchid'),
  ('Cataleya','Spanish botanical','cattleya orchid'),
  ('Catalina','Greek via Spanish','pure'),
  ('Kaitlyn','Greek via Irish / English','pure'),
  ('Katelyn','Greek via English','pure'),
  ('Kallie','Greek / English','beautiful'),
  ('Callie','Greek / English','beautiful'),
  ('Kalani','Hawaiian','the heavens; royal one'),
  ('Kailani','Hawaiian','sea and sky'),
  ('Kailany','Hawaiian-inspired modern spelling','sea and sky'),
  ('Leilani','Hawaiian','heavenly flower; royal child'),
  ('Leilany','Hawaiian-inspired modern spelling','heavenly flower; royal child'),
  ('Milani','Hawaiian','gentle caress; heavenly beauty'),
  ('Meilani','Hawaiian','beautiful heavenly flower'),
  ('Nalani','Hawaiian','the heavens; calm skies'),
  ('Noemi','Hebrew via Romance languages','pleasantness'),
  ('Noelle','French','Christmas'),
  ('Nellie','English','bright, shining'),
  ('Ellie','Greek / Hebrew via English','bright, shining; God is my light'),
  ('Elle','French','she'),
  ('Elora','Greek / Hebrew / literary','light; God is my light'),
  ('Elara','Greek','mythological name; meaning uncertain'),
  ('Elowen','Cornish','elm tree'),
  ('Elowyn','Cornish-inspired modern spelling','elm tree'),
  ('Eliora','Hebrew','God is my light'),
  ('Liora','Hebrew','my light'),
  ('Nyla','Arabic / modern usage','one who succeeds; winner'),
  ('Nylah','Arabic / modern usage','one who succeeds; winner'),
  ('Amina','Arabic','trustworthy, faithful'),
  ('Amira','Arabic','princess'),
  ('Samira','Arabic','evening companion'),
  ('Zahra','Arabic','flower; radiant'),
  ('Zaria','Arabic / Slavic','radiance; princess'),
  ('Zariah','Arabic / Hebrew','radiance; God has helped'),
  ('Zariyah','Arabic-inspired modern spelling','radiance'),
  ('Aliyah','Hebrew / Arabic','ascent; exalted'),
  ('Aaliyah','Arabic / Hebrew','exalted; ascent'),
  ('Aniyah','Hebrew / Arabic','God has answered; caring'),
  ('Anaya','Sanskrit / Hebrew','caring; God has answered'),
  ('Anayah','Hebrew / modern usage','God has answered'),
  ('Amiyah','Modern English / Hebrew-inspired','beloved; God''s people'),
  ('Amayah','Modern English / Japanese / Hebrew-inspired','night rain; close to God'),
  ('Amaya','Japanese / Basque','night rain; mother city'),
  ('Ariya','Sanskrit / Persian','noble'),
  ('Ariyah','Sanskrit / Persian','noble'),
  ('Ariah','Hebrew / Italian','lioness; air, melody'),
  ('Aria','Italian / Hebrew','air, melody; lioness'),
  ('Arya','Sanskrit / Persian','noble'),
  ('Sara','Hebrew','princess'),
  ('Sarah','Hebrew','princess'),
  ('Sarai','Hebrew','my princess'),
  ('Sariah','Hebrew','princess of the Lord'),
  ('Sariyah','Arabic / Hebrew','clouds at night; princess'),
  ('Aisha','Arabic','living, alive'),
  ('Fatima','Arabic','one who abstains; daughter of the Prophet Muhammad'),
  ('Khadija','Arabic','premature child; early-born'),
  ('Zainab','Arabic','fragrant flower; father''s precious jewel'),
  ('Yasmin','Persian / Arabic','jasmine flower'),
  ('Yasmine','Persian / Arabic','jasmine flower')
) as v(display_name, origin, meaning)
where n.display_name = v.display_name;

-- Keep unresolved language concise and readable rather than presenting a large warning.
update public.names
set origin = 'Modern usage',
    meaning = 'meaning uncertain'
where ssa_rank between 1 and 1000
  and origin = 'Uncertain / modern usage';

select
  count(*) filter (where ssa_rank between 1 and 1000) as ranked_names,
  count(*) filter (where ssa_rank between 1 and 1000 and origin <> 'Modern usage') as specifically_resolved,
  count(*) filter (where ssa_rank between 1 and 1000 and origin = 'Modern usage') as still_uncertain
from public.names;
